# Numpy


## Basic Intro
 - NumPy is a library to deal with n-dimensional arrays
 - NumPy provides arrays faster than in-built lists
 - it has many in-built functions to deal with matrices, determinant and vector implementation

In [ ]:
import numpy as np

In [ ]:
# creating arrays

mat = np.array(((1,2,3,4), (5,6,7,8), (9,10,11,12)))

In [ ]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
type(mat)

numpy.ndarray

In [ ]:
id(mat) #doesn't change

139705510474640

In [ ]:
mat[0]

array([1, 2, 3, 4])

In [ ]:
id(mat[0]) #changes everytime dynamically

139705510477232

## Slicing

In [4]:
import numpy as np
mat=[[ 3,  2,  1,  4],
       [ 7,  6,  5,  8],
       [11, 10,  9, 12]]

In [5]:
mat[0]

[3, 2, 1, 4]

In [6]:
L = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]

In [7]:
L[0]

[1, 2, 3, 4]

In [8]:
def col(L,j):
  res=[]
  for row in L:
    res.append(row[j]) 
  return res

In [9]:
col(L, 0)

[1, 5, 9]

In [15]:
mat=np.array([[ 3,  2,  1,  4],
       [ 7,  6,  5,  8],
       [11, 10,  9, 12]])

In [16]:
mat[:,0]

array([ 3,  7, 11])

In [17]:
mat[[0,2]] # row operation 

array([[ 3,  2,  1,  4],
       [11, 10,  9, 12]])

In [18]:
mat[[0,2]] = mat[[2,0]]

In [19]:
mat

array([[11, 10,  9, 12],
       [ 7,  6,  5,  8],
       [ 3,  2,  1,  4]])

In [22]:
mat[:,[0,2]] = mat[:,[2,0]]
mat

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

# Pandas

In [ ]:
import pandas as pd

## Basic Intro
 - used to deal with 2D large dataset
 - better than numpy in dataset greater than 